# https://github.com/dkhamsing/awesome_bot
sudo: required

services:
  - docker

script:
  # Link checks
  - docker run -ti --rm -v $PWD:/mnt:ro dkhamsing/awesome_bot --allow-dupe --allow-redirect --skip-save-results `find . -name "*.md"`
